## Customize the test machine
machine:
  java:
    version: openjdk7

  # Add some environment variables
  #environment:
    #CIRCLE_ENV: test
    #DATABASE_URL: postgres://ubuntu:@127.0.0.1:5432/circle_test

## Customize checkout
#checkout:
#  post:
#    - git submodule sync
#    - git submodule update --init # use submodules

## Customize dependencies
dependencies:
  override:
    - make version
    - sysDeps.sh: # note ':' here
        timeout: 300 # fail if command has no output for 5 minutes
    - buildAPK.sh:
        timeout: 60

  # we automatically cache and restore many dependencies between
  # builds. If you need to, you can add custom paths to cache:
  cache_directories:
    - "android-ndk-root"   # relative to the build directory

database:
  override:
    - echo Database skip

## Customize test commands
test:
  override:
    - file assets/cataclysm
    - file *.apk

general:
  artifacts:
    - "com.cataclysmdda.andr.apk" # relative to the build directory
    #- "~/simplecov" # relative to the user's home directory

## Customize deployment commands
#deployment:
#  staging:
#    branch: master
#    heroku:
#      appname: foo-bar-123

## Custom notifications
#notify:
#  webhooks:
#    # A list of hashes representing hooks. Only the url field is supported.
#    - url: https://someurl.com/hooks/circle
